"""Fail-closed payment webhook reconciliation over synthetic data."""

from __future__ import annotations

from quidz.clock import Clock, FakeClock, SystemClock
from quidz.dlq import REASON_CODES, ReasonCode, RetryPolicy, classify, next_delay, should_retry
from quidz.events import (
    CanonicalEvent,
    EventError,
    MalformedEvent,
    Provider,
    UnknownEventType,
    from_adyen,
    from_stripe,
)
from quidz.inbox import (
    ClaimResult,
    DeliveryState,
    DrainReport,
    claim,
    drain,
    drain_until_idle,
    park,
    parked_events,
    receive_adyen,
    receive_stripe,
)
from quidz.ledger import ApplyOutcome, apply_delivery, list_payments, load_payment
from quidz.model import (
    AmountInvariantViolation,
    EffectKind,
    IllegalTransition,
    PaymentState,
    PrematureEvent,
    apply_effect,
    derive_status,
    state_rank,
)
from quidz.money import (
    THREE_DECIMAL,
    ZERO_DECIMAL,
    CurrencyMismatch,
    Money,
    add,
    exponent,
    format_major,
    sub,
)
from quidz.reconcile import (
    DEFAULT_SEVERITIES,
    BreakGlass,
    Direction,
    DriftKind,
    ExceptionReport,
    Finding,
    GateDecision,
    GatePolicy,
    RemotePayment,
    SettlementRow,
    Severity,
    gate,
    reconcile,
    to_json,
    to_text,
)
from quidz.sim import BreakMode, Delivery, Simulator
from quidz.store import SCHEMA_VERSION, connect, init_schema, write_tx
from quidz.verify import (
    STRIPE_DEFAULT_TOLERANCE_SECONDS,
    BadSignature,
    MalformedHeader,
    SignatureError,
    StaleTimestamp,
    adyen_escape,
    adyen_signing_fields,
    adyen_signing_string,
    parse_stripe_signature_header,
    verify_adyen,
    verify_stripe,
)

__version__ = "0.1.0"

__all__ = [
    "DEFAULT_SEVERITIES",
    "REASON_CODES",
    "SCHEMA_VERSION",
    "STRIPE_DEFAULT_TOLERANCE_SECONDS",
    "THREE_DECIMAL",
    "ZERO_DECIMAL",
    "AmountInvariantViolation",
    "ApplyOutcome",
    "BadSignature",
    "BreakGlass",
    "BreakMode",
    "CanonicalEvent",
    "ClaimResult",
    "Clock",
    "CurrencyMismatch",
    "Delivery",
    "DeliveryState",
    "Direction",
    "DrainReport",
    "DriftKind",
    "EffectKind",
    "EventError",
    "ExceptionReport",
    "FakeClock",
    "Finding",
    "GateDecision",
    "GatePolicy",
    "IllegalTransition",
    "MalformedEvent",
    "MalformedHeader",
    "Money",
    "PaymentState",
    "PrematureEvent",
    "Provider",
    "ReasonCode",
    "RemotePayment",
    "RetryPolicy",
    "SettlementRow",
    "Severity",
    "SignatureError",
    "Simulator",
    "StaleTimestamp",
    "SystemClock",
    "UnknownEventType",
    "__version__",
    "add",
    "adyen_escape",
    "adyen_signing_fields",
    "adyen_signing_string",
    "apply_delivery",
    "apply_effect",
    "claim",
    "classify",
    "connect",
    "derive_status",
    "drain",
    "drain_until_idle",
    "exponent",
    "format_major",
    "from_adyen",
    "from_stripe",
    "gate",
    "init_schema",
    "list_payments",
    "load_payment",
    "next_delay",
    "park",
    "parked_events",
    "parse_stripe_signature_header",
    "receive_adyen",
    "receive_stripe",
    "reconcile",
    "should_retry",
    "state_rank",
    "sub",
    "to_json",
    "to_text",
    "verify_adyen",
    "verify_stripe",
    "write_tx",
]
